# Generated by Django 3.2.8 on 2021-11-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='tessiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura:)')),
                ('color', models.FloatField()),
                ('inflamation', models.FloatField(verbose_name='Inflamacion')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.paciente')),
            ],
            options={
                'verbose_name': 'Tejido',
                'verbose_name_plural': 'Tejidos',
            },
        ),
    ]
